name: Build and Publish Images
# This Pipeline is intended to be executed on merge to master
on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
jobs:
  build-and-publish:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      - 
        name: Prepare Tag
        id: tag
        run: |
          echo "::set-output name=datetag::$(date '+%Y%m%d%H%M%S')"
      
      -
        name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          file: ./Dockerfile
          tags: |
            stategetter:testtarget
      
      - 
        name: Run Trivy vulnerability scanner
        id: test
        if: steps.build.outcome == 'success'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'stategetter:testtarget'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      -
        name: Login to DockerHub
        id: login
        if: steps.test.outcome == 'success'
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - 
        name: Publish
        if: |
          steps.test.outcome == 'success' &&
          steps.login.outcome == 'success'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            peachlover/stategetter:latest
            peachlover/stategetter:${{ steps.tag.outputs.datetag }}   
