name: Test stateGetter

on:
  workflow_dispatch:


jobs:
  stategetter:
    name: stateGetter Job
    runs-on: ubuntu-latest
    steps:
      -
        name: stateGetter get
        uses: TFArmada/stateGetter@master
        with:
          filename: state.tfstate
          organization: sumup
          workspace: autosg-classic-live
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      -
        name: verify file
        run: |
          cat state.tfstate | wc -l